import { execFile } from "node:child_process";
import { cp, mkdir, rm, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { promisify } from "node:util";

import type { ToolPackConfig } from "../config.js";
import { resolveWinInstallIdentity } from "./identity.js";
import type { WinPaths } from "./types.js";
import { writeBuiltAppManifest } from "./manifest.js";
import { pathExists } from "./fs.js";

const execFileAsync = promisify(execFile);

export async function runWailsWinBuilder(config: ToolPackConfig, paths: WinPaths, assembledAppRoot: string): Promise<void> {
  const wailsDir = join(config.workspaceRoot, "apps", "desktop-wails");
  const identity = resolveWinInstallIdentity(config);

  process.stderr.write("[tools-pack wails] Syncing config.yml identity...\n");
  const configYmlPath = join(wailsDir, "build", "config.yml");
  let configYml = await readFile(configYmlPath, "utf8");
  configYml = configYml.replace(/productName:\s*".*?"/, `productName: "${identity.displayName}"`);
  configYml = configYml.replace(/productIdentifier:\s*".*?"/, `productIdentifier: "io.open-design.desktop"`);
  await writeFile(configYmlPath, configYml, "utf8");

  const taskfilePath = join(wailsDir, "Taskfile.yml");
  let taskfile = await readFile(taskfilePath, "utf8");
  // Set APP_NAME to displayName so the built binary is named after the channel (e.g. "Open Design Beta")
  taskfile = taskfile.replace(/APP_NAME:\s*".*?"/, `APP_NAME: "${identity.displayName}"`);
  await writeFile(taskfilePath, taskfile, "utf8");

  process.stderr.write("[tools-pack wails] Updating build assets for Windows...\n");
  try {
    await execFileAsync("wails3", [
      "update",
      "build-assets",
      "-name",
      identity.displayName,
      "-binaryname",
      identity.displayName,
      "-config",
      "config.yml",
      "-dir",
      ".",
    ], {
      cwd: join(wailsDir, "build"),
      env: { ...process.env },
    });
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      throw new Error("Wails v3 CLI not found. Please install wails3 using `go install github.com/wailsapp/wails/v3/cmd/wails3@latest`.");
    }
    throw error;
  }

  // Clean up unused build platforms generated by wails3 update
  await rm(join(wailsDir, "build", "linux"), { force: true, recursive: true });
  await rm(join(wailsDir, "build", "ios"), { force: true, recursive: true });
  await rm(join(wailsDir, "build", "android"), { force: true, recursive: true });

  process.stderr.write("[tools-pack wails] Running wails3 task windows:build in apps/desktop-wails...\n");
  try {
    await execFileAsync("wails3", ["task", "windows:build", "ARCH=amd64"], {
      cwd: wailsDir,
      env: { ...process.env },
    });
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      throw new Error("Wails v3 CLI not found. Please install wails3 using `go install github.com/wailsapp/wails/v3/cmd/wails3@latest`.");
    }
    throw error;
  }

  // Copy built binary to standard unpacked directory
  const builtBinaryPath = join(wailsDir, "bin", `${identity.displayName}.exe`);
  
  await rm(paths.appBuilderOutputRoot, { force: true, recursive: true });
  await rm(paths.unpackedRoot, { force: true, recursive: true });
  await mkdir(paths.unpackedRoot, { recursive: true });

  // Copy wails binary to target unpacked path
  await cp(builtBinaryPath, paths.unpackedExePath);

  const resourcesDir = join(paths.unpackedRoot, "resources");
  await mkdir(resourcesDir, { recursive: true });

  // Copy assembled next.js + daemon app into resources/app
  await cp(assembledAppRoot, join(resourcesDir, "app"), { recursive: true });

  // Copy extra resources (like tools-pack does for electron-builder)
  await cp(paths.resourceRoot, join(resourcesDir, "open-design"), { recursive: true });

  // Copy packaged config
  await cp(paths.packagedConfigPath, join(resourcesDir, "open-design-config.json"));

  // Write manifest file
  await writeBuiltAppManifest(paths, {
    appBuilderOutputRoot: paths.appBuilderOutputRoot,
    cacheEntryPath: null,
    configPath: paths.packagedConfigPath,
    executablePath: paths.unpackedExePath,
    source: "namespace",
    unpackedRoot: paths.unpackedRoot,
    webStandaloneHookAuditPath: (await pathExists(paths.webStandaloneHookAuditPath)) ? paths.webStandaloneHookAuditPath : null,
  });

  process.stderr.write(`[tools-pack wails] Assembled wails app successfully at ${paths.unpackedRoot}\n`);
}
